### PR TITLE
Added Google Tag Manager

### PR DESCRIPTION
**Pull request by neoocm**

### CODE REVIEW

**Comment by kostasthebarbarian** [comment]
@neoocm: I built and ran this locally. Page looks ok but I am getting a couple of warnings:

WARN: Unresolved specs during Gem::Specification.reset:
      rouge (~> 1.7)
      jekyll-watch (~> 1.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.

Any ideas?

**Comment by neoocm** [comment]
Have a look and try the solutions proposed here:
http://stackoverflow.com/questions/17936340/unresolved-specs-during-gemspecification-reset

Let me know if that resolves the issue. You might have a different version
of the tools that I have specified in the GemFile. But if you had a
different GemFile you could test using that one and see what happens

On Mon, Nov 21, 2016 at 12:51 PM, Kostas Stamatiou <notifications@github.com

**Comment by kostasthebarbarian** [comment]
bundle clean --force seems to solve the issue.

Another question: do the Gemfile and Gemfile.lock 'override' config.yml?
I want to maintain tracking in Google Analytics.

**Comment by neoocm** [comment]
The gem file only contains compilation dependencies.
config.yml is for jekyll config.
So, no it doesnt override.
But if you have google tag manager you can configure it to include analytics
https://support.google.com/analytics/answer/6163791

**Comment by kostasthebarbarian** [comment]
Cool. I already have it configured to include analytics.

**Pull request merged**
